GULGECSFOLDER = GulgECS
GULGGRAPHICSFOLDER = GulgGraphics
SUBFOLDERS = $(GULGECSFOLDER) $(GULGGRAPHICSFOLDER)
MAKESUFFIX = _make
CLEANSUFFIX = _clean
FOLDERSTOMAKE = $(addsuffix $(MAKESUFFIX), $(SUBFOLDERS))
FOLDERSTOCLEAN = $(addsuffix $(CLEANSUFFIX), $(SUBFOLDERS))

LISTOFCOMPONENTSEXEPATH = ./ListOfComponents/ListOfComponents
GULGTYPESFOLDER = GulgECS/Includes/GulgECS/
GULGSIGNATUREKEEPERPATH = GulgECS/Sources/GulgECS/ComponentSignatureKeeper.cpp

.PHONY: all clean listOfComponents $(FOLDERSTOMAKE) $(FOLDERSTOCLEAN)

all: listOfComponents $(FOLDERSTOMAKE)

listOfComponents:
	@$(LISTOFCOMPONENTSEXEPATH) . $(GULGTYPESFOLDER) $(GULGSIGNATUREKEEPERPATH)

$(FOLDERSTOMAKE):
	@$(MAKE) -C $(subst $(MAKESUFFIX),, $@) --no-print-directory

clean: $(FOLDERSTOCLEAN)

$(FOLDERSTOCLEAN):
	@$(MAKE) clean -C $(subst $(CLEANSUFFIX),, $@) --no-print-directory