GULGECSFOLDER = GulgECS
GULGGRAPHICSFOLDER = GulgGraphics
SUBFOLDERS = $(GULGECSFOLDER) $(GULGGRAPHICSFOLDER)
MAKESUFFIX = _make
CLEANSUFFIX = _clean
FOLDERSTOMAKE = $(addsuffix $(MAKESUFFIX), $(SUBFOLDERS))
FOLDERSTOCLEAN = $(addsuffix $(CLEANSUFFIX), $(SUBFOLDERS))

.PHONY: all clean $(FOLDERSTOMAKE) $(FOLDERSTOCLEAN)

all: $(FOLDERSTOMAKE)

$(FOLDERSTOMAKE):
	@$(MAKE) -C $(subst $(MAKESUFFIX),, $@) --no-print-directory

clean: $(FOLDERSTOCLEAN)

$(FOLDERSTOCLEAN):
	@$(MAKE) clean -C $(subst $(CLEANSUFFIX),, $@) --no-print-directory