#ifndef COMPONENT_TYPES_HPP
#define COMPONENT_TYPES_HPP

//This file was auto_generated by the ListOfComponents program. Please, don't modify it.

namespace Gg {

	namespace Component {

		const uint32_t MaxComponentType = 3;

		enum class Type {

			Drawable,
			Hitbox2D,
			Position
		};
	}
}

#endif
